name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository # You must checkout your repository first.
        uses: actions/checkout@v3

      - name: Publish Package
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          token: ${{ secrets.PYPI_API_TOKEN }}
          build: true
